version: '2'

networks:
  default:
    external:
      name: test-network

services:
  portainer:
    container_name: enersy-web
    build:
      context: .
    ports:
      - "8080:8080"
    restart: always
